In [3]:
from sklearn import datasets
cancer = datasets.load_breast_cancer()

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
cancer.data.shape

(569, 30)

In [7]:
type(cancer)

sklearn.utils.Bunch

In [8]:
df = pd.DataFrame(cancer.data, columns = cancer.feature_names)
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
normalized_df=(cancer.data-cancer.data.min())/(cancer.data.max()-cancer.data.min())

In [11]:
#normalized_df=(cancer.data-cancer.data.mean())/cancer.data.std()

In [12]:
normalized_df.min(),normalized_df.max()

(0.0, 1.0)

In [13]:
normalized_df[0]

array([4.22896098e-03, 2.44005642e-03, 2.88669488e-02, 2.35307945e-01,
       2.78326281e-05, 6.52562294e-05, 7.05453691e-05, 3.45792196e-05,
       5.68641279e-05, 1.85025858e-05, 2.57404795e-04, 2.12811472e-04,
       2.01904090e-03, 3.60601787e-02, 1.50423131e-06, 1.15279737e-05,
       1.26304654e-05, 3.73060649e-06, 7.05923836e-06, 1.45580630e-06,
       5.96614951e-03, 4.07381288e-03, 4.33944523e-02, 4.74612130e-01,
       3.81288199e-05, 1.56464504e-04, 1.67348378e-04, 6.23883404e-05,
       1.08157029e-04, 2.79501646e-05])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(normalized_df, cancer.target, test_size=0.3,random_state=107) # 70% training and 30% test

In [15]:
flatten = np.ravel(X_train)
flatten[np.argmin(X_train)],flatten[np.argmax(X_train)]

(0.0, 1.0)

In [16]:
# The variance is computed for the flattened array by default, otherwise over the specified axis.
X_train.var()

0.0028316344975423866

In [17]:
from sklearn import svm

clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [18]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9064327485380117


In [19]:
y_pred_train = clf.predict(X_train)
print("Accuracy on Training:", metrics.accuracy_score(y_train, y_pred_train))

Accuracy on Training: 0.8592964824120602


In [20]:
# support vectors
clf.support_vectors_

array([[4.42172073e-03, 4.69675599e-03, 2.84203103e-02, ...,
        3.04184297e-05, 6.03432064e-05, 1.34861307e-05],
       [3.49553362e-03, 3.91866479e-03, 2.31875882e-02, ...,
        4.76492713e-05, 8.42736248e-05, 2.50352609e-05],
       [3.24870710e-03, 5.75693465e-03, 2.17042783e-02, ...,
        3.57545839e-05, 8.58251058e-05, 2.78091208e-05],
       ...,
       [3.09355900e-03, 4.82839680e-03, 1.97602257e-02, ...,
        9.86130701e-06, 6.31640809e-05, 1.74635637e-05],
       [3.05124589e-03, 4.54866008e-03, 1.98683592e-02, ...,
        2.31734838e-05, 8.45322050e-05, 2.15467795e-05],
       [2.96661965e-03, 4.03149976e-03, 1.89515750e-02, ...,
        2.31570287e-05, 7.68688293e-05, 1.72308416e-05]])

In [21]:
clf.support_vectors_.shape

(194, 30)

In [22]:
#number of support vector for each class
clf.n_support_

array([97, 97], dtype=int32)

In [23]:
#indexes of suppport vectors
clf.support_

array([  5,   6,   7,   8,  13,  22,  33,  35,  41,  46,  52,  66,  72,
        73,  74,  76,  77,  78,  80,  87,  88,  91,  92,  97, 101, 103,
       104, 114, 115, 119, 120, 124, 126, 134, 138, 145, 150, 161, 168,
       170, 171, 175, 179, 181, 189, 192, 193, 194, 196, 203, 210, 211,
       212, 215, 218, 220, 222, 223, 224, 227, 230, 231, 241, 242, 250,
       253, 257, 259, 267, 273, 276, 281, 284, 294, 297, 300, 304, 305,
       306, 310, 318, 324, 328, 329, 331, 344, 351, 354, 358, 362, 364,
       366, 370, 373, 375, 376, 397,   0,   1,  10,  18,  26,  29,  36,
        40,  53,  58,  60,  61,  65,  71,  75,  85,  86,  90,  95,  98,
       100, 107, 108, 112, 113, 117, 121, 125, 128, 129, 148, 149, 153,
       154, 155, 160, 165, 167, 173, 174, 182, 186, 188, 191, 197, 198,
       204, 205, 208, 214, 217, 226, 229, 238, 239, 246, 247, 248, 256,
       258, 261, 265, 269, 271, 277, 278, 288, 295, 298, 299, 302, 308,
       312, 314, 325, 326, 330, 333, 339, 345, 346, 348, 357, 36

In [24]:
len(clf.support_)

194

In [25]:
# coefficients of the features
clf.coef_

array([[-3.36194498e-02, -7.12492310e-02, -2.62250049e-01,
        -3.35248646e+00, -3.16442768e-04, -1.22382194e-03,
        -1.97834564e-03, -9.19435116e-04, -5.28471142e-04,
        -1.05929001e-04, -4.01896996e-03, -4.49535935e-03,
        -2.75864558e-02, -4.80810747e-01, -3.69845591e-05,
        -2.67739372e-04, -3.84986094e-04, -1.06745932e-04,
        -6.44612981e-05, -2.75101104e-05, -6.40047353e-02,
        -1.27993227e-01, -4.67008094e-01, -6.90329106e+00,
        -6.68592157e-04, -3.89303982e-03, -5.50220553e-03,
        -1.69958950e-03, -1.42292862e-03, -4.25199026e-04]])

In [26]:
len(clf.coef_[0])

30

In [27]:
# coefficients of the support vectors
clf.dual_coef_

array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -0.30594502, -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1. 

In [28]:
clf.dual_coef_.shape

(1, 194)

In [29]:
len(clf.dual_coef_[0])

194

In [30]:
clf.predict([X_train[1]])

array([1])

In [31]:
clf.intercept_

array([2.37655531])

In [32]:
clf.decision_function([X_train[0]])

array([0.4860783])

In [33]:
clf.dual_coef_ @ clf.support_vectors_

array([[-3.36194498e-02, -7.12492310e-02, -2.62250049e-01,
        -3.35248646e+00, -3.16442768e-04, -1.22382194e-03,
        -1.97834564e-03, -9.19435116e-04, -5.28471142e-04,
        -1.05929001e-04, -4.01896996e-03, -4.49535935e-03,
        -2.75864558e-02, -4.80810747e-01, -3.69845591e-05,
        -2.67739372e-04, -3.84986094e-04, -1.06745932e-04,
        -6.44612981e-05, -2.75101104e-05, -6.40047353e-02,
        -1.27993227e-01, -4.67008094e-01, -6.90329106e+00,
        -6.68592157e-04, -3.89303982e-03, -5.50220553e-03,
        -1.69958950e-03, -1.42292862e-03, -4.25199026e-04]])

In [34]:
(clf.dual_coef_ @ clf.support_vectors_).shape

(1, 30)

In [35]:
X_train[0].reshape(1, len(X_train[0])).T

array([[3.46497414e-03],
       [5.97555242e-03],
       [2.22614010e-02],
       [1.57169723e-01],
       [1.94522802e-05],
       [1.69581570e-05],
       [9.64974142e-06],
       [7.11565585e-06],
       [4.32534086e-05],
       [1.33521392e-05],
       [7.12505877e-05],
       [3.25575929e-04],
       [5.11753644e-04],
       [6.44334744e-03],
       [1.12247297e-06],
       [2.75505407e-06],
       [4.57686883e-06],
       [2.98307475e-06],
       [4.39586272e-06],
       [6.17301363e-07],
       [3.88105313e-03],
       [7.59050306e-03],
       [2.52468265e-02],
       [1.94264222e-01],
       [2.49177245e-05],
       [3.23460273e-05],
       [3.78702398e-05],
       [2.57404795e-05],
       [6.39868359e-05],
       [1.63516690e-05]])

In [36]:
X_train[0].reshape(1, len(X_train[0])).T.shape

(30, 1)

In [37]:
(clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T

array([[-1.89047701]])

In [38]:
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[1].reshape(1, len(X_train[1])).T + clf.intercept_)[0][0]

0.7999758604849831

A partir daqui não é mais do Thiago

**Encontrando Limites Positivo e Negativo do SVM**

In [39]:
decfun = clf.decision_function(X_train)
lim_pos = decfun[np.argmax(decfun)]
lim_neg = decfun[np.argmin(decfun)]
print("Limite Pos = ",lim_pos, '\nLimite Neg =',lim_neg)

Limite Pos =  1.8675370149765804 
Limite Neg = -6.600371124175772


**Preparando variáveis wr, t1, t2**

In [40]:
wr = []
for i in range(1,13):
  wr.append(i*0.04)
print(wr)

[0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48]


In [41]:
#Total quantity of elements
n_elements = decfun.shape[0]
n_elements

398

In [42]:
t1 = []
t2 = []
for i in range (1,101):
  t1.append(0.01*i*lim_pos)
  t2.append(0.01*i*lim_neg)
#for i in range (1,51):
#  t1.append(0.02*i*lim_pos)
#  t2.append(0.02*i*lim_neg)

In [43]:
dict_reject = {'WR': wr,'T1':t1, 'T2':t2,'E':[],'R':[],'EWRR': []}
dict_reject

{'E': [],
 'EWRR': [],
 'R': [],
 'T1': [0.018675370149765804,
  0.03735074029953161,
  0.05602611044929741,
  0.07470148059906322,
  0.09337685074882902,
  0.11205222089859482,
  0.13072759104836065,
  0.14940296119812643,
  0.16807833134789224,
  0.18675370149765805,
  0.20542907164742386,
  0.22410444179718964,
  0.24277981194695547,
  0.2614551820967213,
  0.28013055224648703,
  0.29880592239625287,
  0.3174812925460187,
  0.3361566626957845,
  0.35483203284555026,
  0.3735074029953161,
  0.3921827731450819,
  0.4108581432948477,
  0.4295335134446135,
  0.44820888359437927,
  0.4668842537441451,
  0.48555962389391094,
  0.5042349940436768,
  0.5229103641934426,
  0.5415857343432083,
  0.5602611044929741,
  0.5789364746427399,
  0.5976118447925057,
  0.6162872149422716,
  0.6349625850920374,
  0.6536379552418032,
  0.672313325391569,
  0.6909886955413348,
  0.7096640656911005,
  0.7283394358408664,
  0.7470148059906322,
  0.765690176140398,
  0.7843655462901638,
  0.8030409164399296

First Element Iteration Example

In [44]:
#Get Number of Rejected
positive_indexes = np.where(decfun >= dict_reject['T1'][0])
negative_indexes = np.where(decfun < dict_reject['T2'][0])
rejected_indexes = np.where((decfun < dict_reject['T1'][0]) & (decfun >= dict_reject['T2'][0]))
R = rejected_indexes[0].shape[0]
np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

((1, 301), (1, 91), 6)

In [45]:
#Showing Rejected Elements
rejected_indexes,decfun[rejected_indexes[0]],dict_reject['T1'][0],dict_reject['T2'][0]

((array([ 35,  74,  76, 193, 227, 265]),),
 array([-0.03581548,  0.00658618, -0.01019755, -0.01446095, -0.0559994 ,
        -0.01857772]),
 0.018675370149765804,
 -0.06600371124175772)

In [46]:
#Get Number of Misclassifications
class_p = y_train[positive_indexes]
class_n = y_train[negative_indexes]
error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
error_total = (error_p + error_n)/(n_elements - R)
class_p,class_n,error_p,error_n,error_total,

(array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [47]:
print("Erro = ",error_total," wr = ",dict_reject['WR'][0],' R = ',R, '\nE + wr * R = ',error_total + dict_reject['WR'][0] * R)

Erro =  0.1377551020408163  wr =  0.04  R =  6 
E + wr * R =  0.3777551020408163


First Full Iterations

In [48]:
EwrR_0 = []
for i,t in enumerate(dict_reject['T1']):
  #Get Number of Rejected
  positive_indexes = np.where(decfun >= dict_reject['T1'][i])
  negative_indexes = np.where(decfun < dict_reject['T2'][i])
  rejected_indexes = np.where((decfun < dict_reject['T1'][i]) & (decfun >= dict_reject['T2'][i]))
  R = rejected_indexes[0].shape[0]
  #np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

  #Get Number of Misclassifications
  class_p = y_train[positive_indexes]
  class_n = y_train[negative_indexes]
  error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
  error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
  error_total = (error_p + error_n)/(n_elements - R)
  
  EwrR_0.append(error_total + dict_reject['WR'][0] * R)
  print('(',i+1,')',"Erro = ",error_total," wr = ",dict_reject['WR'][0],' R = ',R, 'E + wrR = ',error_total + dict_reject['WR'][0] * R,' T1 = ',dict_reject['T1'][i], ' T2 = ', dict_reject['T2'][i], ' Error P = ', error_p, ' Error N = ', error_n)
np.argmin(np.array(EwrR_0)), EwrR_0[np.argmin(np.array(EwrR_0))]


( 1 ) Erro =  0.1377551020408163  wr =  0.04  R =  6 E + wrR =  0.3777551020408163  T1 =  0.018675370149765804  T2 =  -0.06600371124175772  Error P =  54  Error N =  0
( 2 ) Erro =  0.13624678663239073  wr =  0.04  R =  9 E + wrR =  0.49624678663239075  T1 =  0.03735074029953161  T2 =  -0.13200742248351544  Error P =  53  Error N =  0
( 3 ) Erro =  0.13695090439276486  wr =  0.04  R =  11 E + wrR =  0.5769509043927649  T1 =  0.05602611044929741  T2 =  -0.19801113372527315  Error P =  53  Error N =  0
( 4 ) Erro =  0.13766233766233765  wr =  0.04  R =  13 E + wrR =  0.6576623376623376  T1 =  0.07470148059906322  T2 =  -0.26401484496703087  Error P =  53  Error N =  0
( 5 ) Erro =  0.1345646437994723  wr =  0.04  R =  19 E + wrR =  0.8945646437994723  T1 =  0.09337685074882902  T2 =  -0.3300185562087886  Error P =  51  Error N =  0
( 6 ) Erro =  0.136  wr =  0.04  R =  23 E + wrR =  1.056  T1 =  0.11205222089859482  T2 =  -0.3960222674505463  Error P =  51  Error N =  0
( 7 ) Erro =  0.1

(0, 0.3777551020408163)

All Iterations

In [49]:
for i,wr_ in enumerate(dict_reject['WR']):
  EwrR = []
  for i,t in enumerate(dict_reject['T1']):
    #Get Number of Rejected
    positive_indexes = np.where(decfun >= dict_reject['T1'][i])
    negative_indexes = np.where(decfun < dict_reject['T2'][i])
    rejected_indexes = np.where((decfun < dict_reject['T1'][i]) & (decfun >= dict_reject['T2'][i]))
    R = rejected_indexes[0].shape[0]
    #np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

    #Get Number of Misclassifications
    class_p = y_train[positive_indexes]
    class_n = y_train[negative_indexes]
    error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
    error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
    error_total = (error_p + error_n)/(n_elements - R)
    
    EwrR.append(error_total + wr_ * R)
    #print('(',i+1,')',"Erro = ",error_total," wr = ",wr_,' R = ',R, 'E + wrR = ',error_total + wr_ * R,' T1 = ',dict_reject['T1'][i], ' T2 = ', dict_reject['T2'][i], ' Error P = ', error_p, ' Error N = ', error_n)
  print(np.argmin(np.array(EwrR)), EwrR[np.argmin(np.array(EwrR))])

0 0.3777551020408163
0 0.6177551020408163
0 0.8577551020408163
0 1.0977551020408163
0 1.3377551020408165
0 1.5777551020408163
0 1.8177551020408165
0 2.057755102040816
0 2.2977551020408162
0 2.5377551020408164
0 2.7777551020408167
0 3.017755102040816


z3 solver thiago

In [50]:
#!pip install z3-solver

In [51]:
from z3 import *

In [52]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [53]:
# creating one z3 variable for each feature in the dataset
dict_vars = {}
for feature in cancer.feature_names:
  dict_vars[feature] = Real(feature)

In [54]:
dict_vars

{'area error': area error,
 'compactness error': compactness error,
 'concave points error': concave points error,
 'concavity error': concavity error,
 'fractal dimension error': fractal dimension error,
 'mean area': mean area,
 'mean compactness': mean compactness,
 'mean concave points': mean concave points,
 'mean concavity': mean concavity,
 'mean fractal dimension': mean fractal dimension,
 'mean perimeter': mean perimeter,
 'mean radius': mean radius,
 'mean smoothness': mean smoothness,
 'mean symmetry': mean symmetry,
 'mean texture': mean texture,
 'perimeter error': perimeter error,
 'radius error': radius error,
 'smoothness error': smoothness error,
 'symmetry error': symmetry error,
 'texture error': texture error,
 'worst area': worst area,
 'worst compactness': worst compactness,
 'worst concave points': worst concave points,
 'worst concavity': worst concavity,
 'worst fractal dimension': worst fractal dimension,
 'worst perimeter': worst perimeter,
 'worst radius': w

In [55]:
dict_vars['area error']

area error

In [56]:
constraints = Solver()

In [57]:
constraints.add(dict_vars['area error'] > 2)
constraints.add(dict_vars['compactness error'] < 10)
constraints.add(dict_vars['compactness error'] > 2)
constraints.add(dict_vars['area error'] * dict_vars['compactness error'] == 27)

In [58]:
constraints.check()

sat

In [59]:
constraints.model()

[compactness error = 3, area error = 9]

Implementing SVM function for Z3 Solver

In [60]:
X_train.shape

(398, 30)

In [61]:
#SVM Decision Function answer for the first element of training set and the actual first element
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_), decfun[0]

(array([[0.4860783]]), 0.48607829979011474)

In [62]:
clf.dual_coef_.shape,clf.support_vectors_.shape,X_train[0].reshape(1, len(X_train[0])).T.shape, clf.intercept_

((1, 194), (194, 30), (30, 1), array([2.37655531]))

In [63]:
#SVM Decision Function answer for all elements of training set
for i in range(0,X_train.shape[0]):
  #print(i, ' : ',((clf.dual_coef_ @ clf.support_vectors_) @ X_train[i].reshape(1, len(X_train[0])).T + clf.intercept_))
  pass

To z3

In [64]:
np.RealVal = np.vectorize(RealVal) # simple mapping of functions over a vector
np.RealVector = np.vectorize(RealVector) 

In [65]:
test_real = Real('X_train')

In [66]:
test_real

X_train

In [67]:
z3_dual_coef = np.RealVal(clf.dual_coef_)
z3_support_vectors = np.RealVal(clf.support_vectors_)
z3_X_Train = np.RealVal(X_train)
z3_intercept_ = np.RealVal(clf.intercept_)

In [68]:
#O Z3 possui um problema de arredondamento (Floating Point) e não consegue chegar ao valor exato da função de decisão, mas até a oitava casa.
first_element = ((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0]
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] <= first_element)
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] == first_element)
first_element

proved
counterexample
[]


0.4860782997901181

In [69]:
expression = simplify (((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0])
expression

75949734342205826030133587979307173778749138185601332274243/156250000000000000000000000000000000000000000000000000000000

In [70]:
expression.numerator_as_long()/expression.denominator_as_long()

0.4860782997901173

In [71]:
get_decimal = float("{0:.9f}".format(expression.numerator_as_long()/expression.denominator_as_long()))
get_decimal

0.4860783

In [72]:
clf.intercept_[0],z3_intercept_[0],z3_intercept_[0].numerator_as_long()/z3_intercept_[0].denominator_as_long()

(2.376555312080476, 594138828020119/250000000000000, 2.376555312080476)

In [73]:
rejected_indexes = np.where((decfun < dict_reject['T1'][0]) & (decfun >= dict_reject['T2'][0]))
decfun[rejected_indexes[0]]

array([-0.03581548,  0.00658618, -0.01019755, -0.01446095, -0.0559994 ,
       -0.01857772])

In [74]:
for index in rejected_indexes[0]:
  expression = simplify (((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[index].reshape(1, len(z3_X_Train[index])).T + z3_intercept_)[0][0])
  expression = expression.numerator_as_long()/expression.denominator_as_long()
  
  print(expression, decfun[index], abs(abs(expression) - abs(decfun[index])))
  #expression = round(expression,6)
  #decfun_value = round(decfun[index],6)
  #print(expression, decfun_value, abs(abs(expression) - abs(decfun_value)))

-0.03581548287200886 -0.03581548287201608 7.223388553967425e-15
0.006586180171712148 0.006586180171711309 8.387388006347862e-16
-0.010197551125943206 -0.010197551125936233 6.9735883734267645e-15
-0.01446094738111508 -0.014460947381113698 1.3825746103535153e-15
-0.05599939940330402 -0.055999399403302785 1.2351231148954867e-15
-0.01857772256331143 -0.018577722563308807 2.6229018956769323e-15


Implemeting Solver's Restrictions

In [75]:
solver = Solver()

In [76]:
z3_X_Train[rejected_indexes[0][0]]

array([690173953925717/200000000000000000,
       23660084626234133/5000000000000000000,
       22270803949224257/1000000000000000000,
       8045369064409967/50000000000000000,
       2899330042313117/125000000000000000000,
       8462623413258109/500000000000000000000,
       17383638928067703/1000000000000000000000,
       2472496473906911/200000000000000000000,
       1864127879642689/50000000000000000000,
       1740126939351199/125000000000000000000,
       277797367183827/2500000000000000000,
       1457451810061119/5000000000000000000,
       1877644569816643/2500000000000000000,
       266807710390221/25000000000000000,
       3360366713681241/2500000000000000000000,
       5463093559003291/2000000000000000000000,
       1174188998589563/250000000000000000000,
       6517395392571697/2500000000000000000000,
       3314527503526093/1000000000000000000000,
       4901269393511989/10000000000000000000000,
       8965679360601787/2000000000000000000,
       3629525152797367/500000

First Element on Z3 Decision Function

In [77]:
first_element = ((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0]
first_element

0.4860782997901181

In [78]:
np.RealVal = np.vectorize(RealVal) 
np.RealVector = np.vectorize(RealVector) 

In [79]:
z3_dual_coef = np.RealVal(clf.dual_coef_)
z3_support_vectors = np.RealVal(clf.support_vectors_)
z3_X_Train = np.RealVal(X_train)
z3_intercept_ = np.RealVal(clf.intercept_)

In [80]:
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] <= first_element)

proved


In [81]:
X_train[0].shape

(30,)

In [82]:
#X_train_t = X_train[0].reshape(1, len(X_train[0])).T

In [83]:
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0], first_element

(0.4860782997901181, 0.4860782997901181)

In [84]:
X_train_2 = X_train[0]
X_train_2[0] = 2

In [85]:
expressao = simplify (((z3_dual_coef @ z3_support_vectors) @ X_train_2.reshape(1, len(X_train_2)).T + z3_intercept_)[0][0])

In [86]:
expressao.numerator_as_long()/expressao.denominator_as_long()

0.41895589068639616

In [87]:
prove(((z3_dual_coef @ z3_support_vectors) @ X_train[0].reshape(1, len(X_train[0])).T + z3_intercept_)[0][0] <= first_element)

proved


In [88]:
for i in range (0, len(X_train[0])):
  print('solver.add(z3_X_Train[',i,'] == X_train[0][',i,']')

solver.add(z3_X_Train[ 0 ] == X_train[0][ 0 ]
solver.add(z3_X_Train[ 1 ] == X_train[0][ 1 ]
solver.add(z3_X_Train[ 2 ] == X_train[0][ 2 ]
solver.add(z3_X_Train[ 3 ] == X_train[0][ 3 ]
solver.add(z3_X_Train[ 4 ] == X_train[0][ 4 ]
solver.add(z3_X_Train[ 5 ] == X_train[0][ 5 ]
solver.add(z3_X_Train[ 6 ] == X_train[0][ 6 ]
solver.add(z3_X_Train[ 7 ] == X_train[0][ 7 ]
solver.add(z3_X_Train[ 8 ] == X_train[0][ 8 ]
solver.add(z3_X_Train[ 9 ] == X_train[0][ 9 ]
solver.add(z3_X_Train[ 10 ] == X_train[0][ 10 ]
solver.add(z3_X_Train[ 11 ] == X_train[0][ 11 ]
solver.add(z3_X_Train[ 12 ] == X_train[0][ 12 ]
solver.add(z3_X_Train[ 13 ] == X_train[0][ 13 ]
solver.add(z3_X_Train[ 14 ] == X_train[0][ 14 ]
solver.add(z3_X_Train[ 15 ] == X_train[0][ 15 ]
solver.add(z3_X_Train[ 16 ] == X_train[0][ 16 ]
solver.add(z3_X_Train[ 17 ] == X_train[0][ 17 ]
solver.add(z3_X_Train[ 18 ] == X_train[0][ 18 ]
solver.add(z3_X_Train[ 19 ] == X_train[0][ 19 ]
solver.add(z3_X_Train[ 20 ] == X_train[0][ 20 ]
solver.add(z

In [89]:
z3_X_Train = np.RealVector('x',X_train.shape[1])
z3_X_Train,z3_X_Train[0]

(array([x__0, x__1, x__2, x__3, x__4, x__5, x__6, x__7, x__8, x__9, x__10,
        x__11, x__12, x__13, x__14, x__15, x__16, x__17, x__18, x__19,
        x__20, x__21, x__22, x__23, x__24, x__25, x__26, x__27, x__28,
        x__29], dtype=object), x__0)

In [90]:
z3_X_Train[:3] @ z3_X_Train[:3]

x__0*x__0 + x__1*x__1 + x__2*x__2

In [91]:
X_train[0]

array([2.00000000e+00, 5.97555242e-03, 2.22614010e-02, 1.57169723e-01,
       1.94522802e-05, 1.69581570e-05, 9.64974142e-06, 7.11565585e-06,
       4.32534086e-05, 1.33521392e-05, 7.12505877e-05, 3.25575929e-04,
       5.11753644e-04, 6.44334744e-03, 1.12247297e-06, 2.75505407e-06,
       4.57686883e-06, 2.98307475e-06, 4.39586272e-06, 6.17301363e-07,
       3.88105313e-03, 7.59050306e-03, 2.52468265e-02, 1.94264222e-01,
       2.49177245e-05, 3.23460273e-05, 3.78702398e-05, 2.57404795e-05,
       6.39868359e-05, 1.63516690e-05])

In [92]:
solver = Solver()

#solver.add(z3_X_Train[0] > -5)
#solver.add(z3_X_Train[0] < 0)
solver.add(z3_X_Train[1] == X_train[0][1])
solver.add(z3_X_Train[2] == X_train[0][2])
solver.add(z3_X_Train[3] == X_train[0][3])
solver.add(z3_X_Train[4] == X_train[0][4])
solver.add(z3_X_Train[5] == X_train[0][5])
solver.add(z3_X_Train[6] == X_train[0][6])
solver.add(z3_X_Train[7] == X_train[0][7])
solver.add(z3_X_Train[8] == X_train[0][8])
solver.add(z3_X_Train[9] == X_train[0][9])
solver.add(z3_X_Train[10] == X_train[0][10])
solver.add(z3_X_Train[11] == X_train[0][11])
solver.add(z3_X_Train[12] == X_train[0][12])
solver.add(z3_X_Train[13] == X_train[0][13])
solver.add(z3_X_Train[14] == X_train[0][14])
solver.add(z3_X_Train[15] == X_train[0][15])
solver.add(z3_X_Train[16] == X_train[0][16])
solver.add(z3_X_Train[17] == X_train[0][17])
solver.add(z3_X_Train[18] == X_train[0][18])
solver.add(z3_X_Train[19] == X_train[0][19])
solver.add(z3_X_Train[20] == X_train[0][20])
solver.add(z3_X_Train[21] == X_train[0][21])
solver.add(z3_X_Train[22] == X_train[0][22])
solver.add(z3_X_Train[23] == X_train[0][23])
solver.add(z3_X_Train[24] == X_train[0][24])
solver.add(z3_X_Train[25] == X_train[0][25])
solver.add(z3_X_Train[26] == X_train[0][26])
solver.add(z3_X_Train[27] == X_train[0][27])
solver.add(z3_X_Train[28] == X_train[0][28])
solver.add(z3_X_Train[29] == X_train[0][29])

In [93]:
first_element

0.4860782997901181

In [94]:
solver.add(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < 0)

In [95]:
solver.check(), solver.model()

(sat, [x__16 = 915373765867419/200000000000000000000,
  x__4 = 1945228020686413/100000000000000000000,
  x__20 = 1940526563234603/500000000000000000,
  x__21 = 7590503055947343/1000000000000000000,
  x__15 = 344381758345087/125000000000000000000,
  x__6 = 9649741419840151/1000000000000000000000,
  x__23 = 4856605547719793/25000000000000000,
  x__2 = 17391719558063/781250000000000,
  x__19 = 6173013634226609/10000000000000000000000,
  x__13 = 6443347437705689/1000000000000000000,
  x__14 = 280618241654913/250000000000000000000,
  x__10 = 7125058768218147/100000000000000000000,
  x__1 = 1493888105312647/250000000000000000,
  x__9 = 6676069581570287/500000000000000000000,
  x__24 = 622943112364833/25000000000000000000,
  x__11 = 1302303714151387/4000000000000000000,
  x__8 = 540667606958157/12500000000000000000,
  x__5 = 1695815702867889/100000000000000000000,
  x__22 = 2524682651622003/100000000000000000,
  x__26 = 946755994358251/25000000000000000000,
  x__27 = 6435119887165021/25000000

Z3 with Reject Option

In [96]:
X_train.shape[1]

30

In [97]:
t1 = 0.03069242520015834
t2 = -0.22086343489508029

In [98]:
rejected_indexes,rejected_indexes[0][0], rejected_indexes[0].shape, len(rejected_indexes[0])

((array([ 35,  74,  76, 193, 227, 265]),), 35, (6,), 6)

In [99]:
rejected_indexes2 = rejected_indexes[0]
rejected_indexes2

array([ 35,  74,  76, 193, 227, 265])

In [100]:
X_train[rejected_indexes2[0]]

array([3.45086977e-03, 4.73201693e-03, 2.22708039e-02, 1.60907381e-01,
       2.31946403e-05, 1.69252468e-05, 1.73836389e-05, 1.23624824e-05,
       3.72825576e-05, 1.39210155e-05, 1.11118947e-04, 2.91490362e-04,
       7.51057828e-04, 1.06723084e-02, 1.34414669e-06, 2.73154678e-06,
       4.69675599e-06, 2.60695816e-06, 3.31452750e-06, 4.90126939e-07,
       4.48283968e-03, 7.25905031e-03, 2.90079925e-02, 2.67512929e-01,
       3.44146685e-05, 4.39821345e-05, 6.85002351e-05, 3.78232252e-05,
       7.12035731e-05, 1.93135872e-05])

In [101]:
for i in range (0, len(X_train[0])):
  print('solver.add(z3_X_Train[',i,'] == X_train[rejected_indexes2[0]][',i,']')

solver.add(z3_X_Train[ 0 ] == X_train[rejected_indexes2[0]][ 0 ]
solver.add(z3_X_Train[ 1 ] == X_train[rejected_indexes2[0]][ 1 ]
solver.add(z3_X_Train[ 2 ] == X_train[rejected_indexes2[0]][ 2 ]
solver.add(z3_X_Train[ 3 ] == X_train[rejected_indexes2[0]][ 3 ]
solver.add(z3_X_Train[ 4 ] == X_train[rejected_indexes2[0]][ 4 ]
solver.add(z3_X_Train[ 5 ] == X_train[rejected_indexes2[0]][ 5 ]
solver.add(z3_X_Train[ 6 ] == X_train[rejected_indexes2[0]][ 6 ]
solver.add(z3_X_Train[ 7 ] == X_train[rejected_indexes2[0]][ 7 ]
solver.add(z3_X_Train[ 8 ] == X_train[rejected_indexes2[0]][ 8 ]
solver.add(z3_X_Train[ 9 ] == X_train[rejected_indexes2[0]][ 9 ]
solver.add(z3_X_Train[ 10 ] == X_train[rejected_indexes2[0]][ 10 ]
solver.add(z3_X_Train[ 11 ] == X_train[rejected_indexes2[0]][ 11 ]
solver.add(z3_X_Train[ 12 ] == X_train[rejected_indexes2[0]][ 12 ]
solver.add(z3_X_Train[ 13 ] == X_train[rejected_indexes2[0]][ 13 ]
solver.add(z3_X_Train[ 14 ] == X_train[rejected_indexes2[0]][ 14 ]
solver.add(z3_X

In [102]:
solver = Solver()

#solver.add(z3_X_Train[0] > -5)
#solver.add(z3_X_Train[0] < 0)
solver.add(z3_X_Train[1] == X_train[rejected_indexes2[0]][1])
solver.add(z3_X_Train[2] == X_train[rejected_indexes2[0]][2])
solver.add(z3_X_Train[3] == X_train[rejected_indexes2[0]][3])
solver.add(z3_X_Train[4] == X_train[rejected_indexes2[0]][4])
solver.add(z3_X_Train[5] == X_train[rejected_indexes2[0]][5])
solver.add(z3_X_Train[6] == X_train[rejected_indexes2[0]][6])
solver.add(z3_X_Train[7] == X_train[rejected_indexes2[0]][7])
solver.add(z3_X_Train[8] == X_train[rejected_indexes2[0]][8])
solver.add(z3_X_Train[9] == X_train[rejected_indexes2[0]][9])
solver.add(z3_X_Train[10] == X_train[rejected_indexes2[0]][10])
solver.add(z3_X_Train[11] == X_train[rejected_indexes2[0]][11])
solver.add(z3_X_Train[12] == X_train[rejected_indexes2[0]][12])
solver.add(z3_X_Train[13] == X_train[rejected_indexes2[0]][13])
solver.add(z3_X_Train[14] == X_train[rejected_indexes2[0]][14])
solver.add(z3_X_Train[15] == X_train[rejected_indexes2[0]][15])
solver.add(z3_X_Train[16] == X_train[rejected_indexes2[0]][16])
solver.add(z3_X_Train[17] == X_train[rejected_indexes2[0]][17])
solver.add(z3_X_Train[18] == X_train[rejected_indexes2[0]][18])
solver.add(z3_X_Train[19] == X_train[rejected_indexes2[0]][19])
solver.add(z3_X_Train[20] == X_train[rejected_indexes2[0]][20])
solver.add(z3_X_Train[21] == X_train[rejected_indexes2[0]][21])
solver.add(z3_X_Train[22] == X_train[rejected_indexes2[0]][22])
solver.add(z3_X_Train[23] == X_train[rejected_indexes2[0]][23])
solver.add(z3_X_Train[24] == X_train[rejected_indexes2[0]][24])
solver.add(z3_X_Train[25] == X_train[rejected_indexes2[0]][25])
solver.add(z3_X_Train[26] == X_train[rejected_indexes2[0]][26])
solver.add(z3_X_Train[27] == X_train[rejected_indexes2[0]][27])
solver.add(z3_X_Train[28] == X_train[rejected_indexes2[0]][28])
solver.add(z3_X_Train[29] == X_train[rejected_indexes2[0]][29])

In [103]:
solver.add(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] > t1)

In [104]:
print(i,solver.check(),solver.model())

29 sat [x__16 = 1174188998589563/250000000000000000000,
 x__4 = 2899330042313117/125000000000000000000,
 x__20 = 8965679360601787/2000000000000000000,
 x__21 = 3629525152797367/500000000000000000,
 x__15 = 5463093559003291/2000000000000000000000,
 x__6 = 17383638928067703/1000000000000000000000,
 x__23 = 5350258580159849/20000000000000000,
 x__2 = 22270803949224257/1000000000000000000,
 x__19 = 4901269393511989/10000000000000000000000,
 x__13 = 266807710390221/25000000000000000,
 x__14 = 3360366713681241/2500000000000000000000,
 x__10 = 277797367183827/2500000000000000000,
 x__1 = 23660084626234133/5000000000000000000,
 x__9 = 1740126939351199/125000000000000000000,
 x__24 = 688293370944993/20000000000000000000,
 x__11 = 1457451810061119/5000000000000000000,
 x__8 = 1864127879642689/50000000000000000000,
 x__5 = 8462623413258109/500000000000000000000,
 x__22 = 362599905970851/12500000000000000,
 x__26 = 3425011753643629/50000000000000000000,
 x__27 = 1891161259990597/500000000000000000

Basic Restrictions

In [105]:
solver2 = Solver()
index_list = []
for i in range(0,len(z3_X_Train)):
  index_list.append(i)
  solver2.add(z3_X_Train[i] >=0)
  solver2.add(z3_X_Train[i] <=1)
solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
           ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))

In [106]:
z3_X_Train

array([x__0, x__1, x__2, x__3, x__4, x__5, x__6, x__7, x__8, x__9, x__10,
       x__11, x__12, x__13, x__14, x__15, x__16, x__17, x__18, x__19,
       x__20, x__21, x__22, x__23, x__24, x__25, x__26, x__27, x__28,
       x__29], dtype=object)

In [107]:
solver2.assertions

<bound method Solver.assertions of [x__0 >= 0,
 x__0 <= 1,
 x__1 >= 0,
 x__1 <= 1,
 x__2 >= 0,
 x__2 <= 1,
 x__3 >= 0,
 x__3 <= 1,
 x__4 >= 0,
 x__4 <= 1,
 x__5 >= 0,
 x__5 <= 1,
 x__6 >= 0,
 x__6 <= 1,
 x__7 >= 0,
 x__7 <= 1,
 x__8 >= 0,
 x__8 <= 1,
 x__9 >= 0,
 x__9 <= 1,
 x__10 >= 0,
 x__10 <= 1,
 x__11 >= 0,
 x__11 <= 1,
 x__12 >= 0,
 x__12 <= 1,
 x__13 >= 0,
 x__13 <= 1,
 x__14 >= 0,
 x__14 <= 1,
 x__15 >= 0,
 x__15 <= 1,
 x__16 >= 0,
 x__16 <= 1,
 x__17 >= 0,
 x__17 <= 1,
 x__18 >= 0,
 x__18 <= 1,
 x__19 >= 0,
 x__19 <= 1,
 x__20 >= 0,
 x__20 <= 1,
 x__21 >= 0,
 x__21 <= 1,
 x__22 >= 0,
 x__22 <= 1,
 x__23 >= 0,
 x__23 <= 1,
 x__24 >= 0,
 x__24 <= 1,
 x__25 >= 0,
 x__25 <= 1,
 x__26 >= 0,
 x__26 <= 1,
 x__27 >= 0,
 x__27 <= 1,
 x__28 >= 0,
 x__28 <= 1,
 x__29 >= 0,
 x__29 <= 1,
 Or(... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    ... +
    .

In [108]:
len(rejected_indexes2)

6

Finding Important Features

In [109]:
z3_X_Train

array([x__0, x__1, x__2, x__3, x__4, x__5, x__6, x__7, x__8, x__9, x__10,
       x__11, x__12, x__13, x__14, x__15, x__16, x__17, x__18, x__19,
       x__20, x__21, x__22, x__23, x__24, x__25, x__26, x__27, x__28,
       x__29], dtype=object)

In [110]:
X_train[rejected_indexes2[0]]

array([3.45086977e-03, 4.73201693e-03, 2.22708039e-02, 1.60907381e-01,
       2.31946403e-05, 1.69252468e-05, 1.73836389e-05, 1.23624824e-05,
       3.72825576e-05, 1.39210155e-05, 1.11118947e-04, 2.91490362e-04,
       7.51057828e-04, 1.06723084e-02, 1.34414669e-06, 2.73154678e-06,
       4.69675599e-06, 2.60695816e-06, 3.31452750e-06, 4.90126939e-07,
       4.48283968e-03, 7.25905031e-03, 2.90079925e-02, 2.67512929e-01,
       3.44146685e-05, 4.39821345e-05, 6.85002351e-05, 3.78232252e-05,
       7.12035731e-05, 1.93135872e-05])

Fixed List

In [111]:
for i in range(0, len(rejected_indexes2)):
  #Add Assertions for 0<= feature <= 1
  index_list = list(range(30))

  #Select a feature and unfix it
  for z in range(0, len(z3_X_Train)):
    solver2 = Solver()
    solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
            ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))
    for j in range(0, len(z3_X_Train)):
      solver2.add(z3_X_Train[j] >=0)
      solver2.add(z3_X_Train[j] <=1)
    for j in range(0, len(z3_X_Train)):
      if j != z: #Choose one to check influence
        solver2.add(z3_X_Train[j] == X_train[rejected_indexes2[i]][j])

    check = solver2.check()
    if check == sat:
      model = solver2.model()
      print('i = ',i,z, check, X_train[rejected_indexes2[i]][z], model[z3_X_Train[z]].numerator_as_long()/model[z3_X_Train[z]].denominator_as_long())
      #print(z, check)
    else:
      index_list.remove(z)
      print('i = ',i, z, check)
  print("Relevant: ",index_list)

i =  0 0 unsat
i =  0 1 unsat
i =  0 2 sat 0.022270803949224257 0.8639436340441322
i =  0 3 sat 0.16090738128819934 0.608052303508685
i =  0 4 unsat
i =  0 5 unsat
i =  0 6 unsat
i =  0 7 unsat
i =  0 8 unsat
i =  0 9 unsat
i =  0 10 unsat
i =  0 11 unsat
i =  0 12 unsat
i =  0 13 sat 0.01067230841560884 0.6977694069127598
i =  0 14 unsat
i =  0 15 unsat
i =  0 16 unsat
i =  0 17 unsat
i =  0 18 unsat
i =  0 19 unsat
i =  0 20 unsat
i =  0 21 unsat
i =  0 22 sat 0.02900799247766808 0.7126247079616702
i =  0 23 sat 0.26751292900799245 0.6471593436913698
i =  0 24 unsat
i =  0 25 unsat
i =  0 26 unsat
i =  0 27 unsat
i =  0 28 unsat
i =  0 29 unsat
Relevant:  [2, 3, 13, 22, 23]
i =  1 0 unsat
i =  1 1 unsat
i =  1 2 sat 0.02152327221438646 0.9444119180979011
i =  1 3 sat 0.14052656323460272 0.6041858071237965
i =  1 4 unsat
i =  1 5 unsat
i =  1 6 unsat
i =  1 7 unsat
i =  1 8 unsat
i =  1 9 unsat
i =  1 10 unsat
i =  1 11 unsat
i =  1 12 unsat
i =  1 13 sat 0.012393041842971322 0.742723

In [ ]:
index_list = list(range(30))
index_list2 = [2, 3, 13, 22, 23]
for element in index_list:
  if element not in index_list2:
    print(element)

Unfixed List, Crescent

In [130]:
for i in range(0, len(rejected_indexes2)):
  #Add Assertions for 0<= feature <= 1
  index_list = list(range(30))
  index_list2 = [2, 3, 13, 22, 23]

  #Select a feature and unfix it
  for z in (range(0, len(z3_X_Train))):
    solver2 = Solver()
    solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
            ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))
    for j in range(0, len(z3_X_Train)):
      solver2.add(z3_X_Train[j] >=0)
      solver2.add(z3_X_Train[j] <=1)
    used_list = []
    for j in range(0, len(z3_X_Train)):    
      if j != z and j in index_list: #Choose one to check influence
        solver2.add(z3_X_Train[j] == X_train[rejected_indexes2[i]][j])
        used_list.append(j)
    #print("Lista utilizada: ",used_list, z3_X_Train)

    check = solver2.check()
    if check == sat:
      model = solver2.model()
      print('i = ',i,z, check, X_train[rejected_indexes2[i]][z], model[z3_X_Train[z]].numerator_as_long()/model[z3_X_Train[z]].denominator_as_long())
      #print(z, check)
    else:
      index_list.remove(z)
      #print('i = ',i, z, check)
  print("Relevant: ",index_list)

i =  0 2 sat 0.022270803949224257 0.80070955443372
i =  0 3 sat 0.16090738128819934 0.514525847523281
i =  0 13 sat 0.01067230841560884 0.5861026933507282
i =  0 20 sat 0.0044828396803008935 1.0
i =  0 21 sat 0.007259050305594734 0.8070316849059577
i =  0 22 sat 0.02900799247766808 0.5976576333106314
i =  0 23 sat 0.26751292900799245 0.42362207093745613
Relevant:  [2, 3, 13, 20, 21, 22, 23]
i =  1 2 sat 0.02152327221438646 0.8812803263395137
i =  1 3 sat 0.14052656323460272 0.5068088890877076
i =  1 13 sat 0.012393041842971322 0.6311186372080994
i =  1 21 sat 0.009837799717912554 0.9753214327025075
i =  1 22 sat 0.030206864127879644 0.6440269754083587
i =  1 23 sat 0.27103902209685005 0.4333408383696964
Relevant:  [2, 3, 13, 21, 22, 23]
i =  2 2 sat 0.024870709920075222 0.8507248874186568
i =  2 3 sat 0.18645980253878702 0.5476998421440317
i =  2 13 sat 0.007820874471086037 0.6112435092499566
i =  2 21 sat 0.005166901739539257 0.9068863041255354
i =  2 22 sat 0.02921955806299953 0.6254

Unfixed List, decrescent

In [131]:
for i in range(0, len(rejected_indexes2)):
  #Add Assertions for 0<= feature <= 1
  index_list = list(range(30))
  index_list2 = [2, 3, 13, 22, 23]

  #Select a feature and unfix it
  for z in reversed((range(0, len(z3_X_Train)))):
    solver2 = Solver()
    solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
            ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))
    for j in range(0, len(z3_X_Train)):
      solver2.add(z3_X_Train[j] >=0)
      solver2.add(z3_X_Train[j] <=1)
    used_list = []
    for j in range(0, len(z3_X_Train)):    
      if j != z and j in index_list: #Choose one to check influence
        solver2.add(z3_X_Train[j] == X_train[rejected_indexes2[i]][j])
        used_list.append(j)
    #print("Lista utilizada: ",used_list, z3_X_Train)

    check = solver2.check()
    if check == sat:
      model = solver2.model()
      print('i = ',i,z, check, X_train[rejected_indexes2[i]][z], model[z3_X_Train[z]].numerator_as_long()/model[z3_X_Train[z]].denominator_as_long())
      #print(z, check)
    else:
      index_list.remove(z)
      #print('i = ',i, z, check)
  print("Relevant: ",index_list)

i =  0 23 sat 0.26751292900799245 0.4385164482735887
i =  0 22 sat 0.02900799247766808 0.7077416159105416
i =  0 20 sat 0.0044828396803008935 1.0
i =  0 13 sat 0.01067230841560884 0.551036862775088
i =  0 3 sat 0.16090738128819934 0.5145171340553686
i =  0 2 sat 0.022270803949224257 0.5155852396788159
i =  0 1 sat 0.0047320169252468266 1.0
i =  0 0 sat 0.003450869769628585 1.0
Relevant:  [0, 1, 2, 3, 13, 20, 22, 23]
i =  1 23 sat 0.27103902209685005 0.4481848682452044
i =  1 22 sat 0.030206864127879644 0.753738841144686
i =  1 13 sat 0.012393041842971322 0.530037791063362
i =  1 12 sat 0.0009188998589562764 0.9159944859995096
i =  1 3 sat 0.14052656323460272 0.5069630341561615
i =  1 2 sat 0.02152327221438646 0.5277627002337122
i =  1 1 sat 0.005582980724024448 1.0
i =  1 0 sat 0.003246356370474847 1.0
Relevant:  [0, 1, 2, 3, 12, 13, 22, 23]
i =  2 23 sat 0.25152797367183827 0.42624254165539993
i =  2 22 sat 0.02921955806299953 0.7352756700083035
i =  2 13 sat 0.007820874471086037 0.50

Not Fixing Individual Lista

In [132]:
for i in range(0, len(rejected_indexes2)):
  #Add Assertions for 0<= feature <= 1
  index_list = list(range(30))
  index_list2 = [2, 3, 13, 22, 23]

  #Select a feature and unfix it
  for z in reversed(range(0, len(z3_X_Train))):
    solver2 = Solver()
    solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
            ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))
    for j in range(0, len(z3_X_Train)):
      solver2.add(z3_X_Train[j] >=0)
      solver2.add(z3_X_Train[j] <=1)
    used_list = []
    for j in range(0, len(z3_X_Train)):    
      if j != z and j in index_list: #Choose one to check influence
        if j not in index_list2:
          solver2.add(z3_X_Train[j] == X_train[rejected_indexes2[i]][j])
          used_list.append(j)
    print("Lista utilizada: ",used_list)

    check = solver2.check()
    if check == sat:
      model = solver2.model()
      print('i = ',i,z, check, X_train[rejected_indexes2[i]][z], model[z3_X_Train[z]].numerator_as_long()/model[z3_X_Train[z]].denominator_as_long())
      #print(z, check)
    else:
      index_list.remove(z)
      print('i = ',i, z, check)
  print("Relevant: ",index_list)

Lista utilizada:  [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 28] [x__0 x__1 x__2 x__3 x__4 x__5 x__6 x__7 x__8 x__9 x__10 x__11 x__12 x__13
 x__14 x__15 x__16 x__17 x__18 x__19 x__20 x__21 x__22 x__23 x__24 x__25
 x__26 x__27 x__28 x__29]
i =  0 29 sat 1.931358721203573e-05 0.0
Lista utilizada:  [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 29] [x__0 x__1 x__2 x__3 x__4 x__5 x__6 x__7 x__8 x__9 x__10 x__11 x__12 x__13
 x__14 x__15 x__16 x__17 x__18 x__19 x__20 x__21 x__22 x__23 x__24 x__25
 x__26 x__27 x__28 x__29]
i =  0 28 sat 7.120357310766338e-05 0.0
Lista utilizada:  [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26, 28, 29] [x__0 x__1 x__2 x__3 x__4 x__5 x__6 x__7 x__8 x__9 x__10 x__11 x__12 x__13
 x__14 x__15 x__16 x__17 x__18 x__19 x__20 x__21 x__22 x__23 x__24 x__25
 x__26 x__27 x__28 x__29]
i =  0 27 sat 3.782322519981194e-05 0.0
Lista utilizada:  [0, 1, 4, 5, 6, 7, 

Fixing Individual List

In [133]:
for i in range(0, len(rejected_indexes2)):
  #Add Assertions for 0<= feature <= 1
  index_list = list(range(30))
  index_list2 = [2, 3, 13, 22, 23]

  #Select a feature and unfix it
  for z in reversed(range(0, len(z3_X_Train))):
    solver2 = Solver()
    solver2.add(Or(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] >= t1,
            ((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < t2))
    for j in range(0, len(z3_X_Train)):
      solver2.add(z3_X_Train[j] >=0)
      solver2.add(z3_X_Train[j] <=1)
    used_list = []
    for j in range(0, len(z3_X_Train)):    
      if j != z and j in index_list2: #Choose one to check influence
        solver2.add(z3_X_Train[j] == X_train[rejected_indexes2[i]][j])
        used_list.append(j)
    print("Lista utilizada: ",used_list)

    check = solver2.check()
    if check == sat:
      model = solver2.model()
      print('i = ',i,z, check, X_train[rejected_indexes2[i]][z], model[z3_X_Train[z]].numerator_as_long()/model[z3_X_Train[z]].denominator_as_long())
      #print(z, check)
    else:
      index_list.remove(z)
      print('i = ',i, z, check)
  print("Relevant: ",index_list)

Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 29 sat 1.931358721203573e-05 1.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 28 sat 7.120357310766338e-05 1.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 27 sat 3.782322519981194e-05 1.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 26 sat 6.850023507287258e-05 1.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 25 sat 4.398213446168312e-05 1.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 24 sat 3.441466854724965e-05 1.0
Lista utilizada:  [2, 3, 13, 22]
i =  0 23 sat 0.26751292900799245 0.4218265827614063
Lista utilizada:  [2, 3, 13, 23]
i =  0 22 sat 0.02900799247766808 0.5843872236338788
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 21 sat 0.007259050305594734 0.7549824982865243
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 20 sat 0.0044828396803008935 0.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 19 sat 4.901269393511989e-07 0.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 18 sat 3.314527503526093e-06 0.0
Lista utilizada:  [2, 3, 13, 22, 23]
i =  0 