In [2]:
from sklearn import datasets
cancer = datasets.load_breast_cancer()

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
cancer.data.shape

(569, 30)

In [6]:
type(cancer)

sklearn.utils.Bunch

In [7]:
df = pd.DataFrame(cancer.data, columns = cancer.feature_names)
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3,random_state=0) # 70% training and 30% test

In [10]:
# The variance is computed for the flattened array by default, otherwise over the specified axis.
X_train.var()

54610.14134314552

In [11]:
from sklearn import svm

clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [12]:
from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9590643274853801


In [13]:
y_pred_train = clf.predict(X_train)
print("Accuracy on Training:", metrics.accuracy_score(y_train, y_pred_train))

Accuracy on Training: 0.964824120603015


In [14]:
# support vectors
clf.support_vectors_

array([[1.499e+01, 2.520e+01, 9.554e+01, ..., 2.899e-02, 1.565e-01,
        5.504e-02],
       [1.245e+01, 1.570e+01, 8.257e+01, ..., 1.741e-01, 3.985e-01,
        1.244e-01],
       [1.626e+01, 2.188e+01, 1.075e+02, ..., 1.047e-01, 2.736e-01,
        7.953e-02],
       ...,
       [1.366e+01, 1.913e+01, 8.946e+01, ..., 1.407e-01, 2.744e-01,
        8.839e-02],
       [1.495e+01, 1.877e+01, 9.784e+01, ..., 8.405e-02, 2.852e-01,
        9.218e-02],
       [1.453e+01, 1.934e+01, 9.425e+01, ..., 9.594e-02, 2.471e-01,
        7.463e-02]])

In [15]:
clf.support_vectors_.shape

(43, 30)

In [16]:
#number of support vector for each class
clf.n_support_

array([21, 22], dtype=int32)

In [17]:
#indexes of suppport vectors
clf.support_

array([ 28,  77,  79,  81, 120, 123, 129, 151, 157, 166, 167, 190, 209,
       216, 264, 279, 284, 349, 364, 379, 393,  11,  15,  53,  68,  80,
        96, 111, 138, 156, 176, 195, 211, 247, 255, 266, 278, 299, 327,
       353, 376, 377, 380], dtype=int32)

In [18]:
len(clf.support_)

43

In [19]:
# coefficients of the features
clf.coef_

array([[ 0.68373455,  0.0488774 , -0.23709621,  0.01686997, -0.22144463,
        -0.18547651, -0.43013893, -0.27241665, -0.38508488, -0.0304932 ,
        -0.03920461,  0.97984896,  0.22443933, -0.07725387, -0.02162182,
         0.13451903,  0.01942884, -0.02275524, -0.0198628 ,  0.0273803 ,
         0.5135781 , -0.2132971 , -0.07484835, -0.00813752, -0.3967954 ,
        -0.55209777, -1.41715509, -0.58011007, -0.81381582, -0.08563459]])

In [20]:
len(clf.coef_[0])

30

In [21]:
# coefficients of the support vectors
clf.dual_coef_

array([[-1.        , -0.03092786, -0.52419775, -1.        , -1.        ,
        -0.65474546, -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -0.79701823,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        ,  1.        ,  0.49046158,  1.        ,  1.        ,
         0.93128035,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  0.28203392,  1.        ,
         0.2324823 ,  1.        ,  0.07063115,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ]])

In [22]:
clf.dual_coef_.shape

(1, 43)

In [23]:
len(clf.dual_coef_[0])

43

In [24]:
clf.predict([X_train[1]])

array([1])

In [25]:
clf.intercept_

array([14.52243574])

In [26]:
clf.decision_function([X_train[0]])

array([3.55261264])

In [27]:
clf.dual_coef_ @ clf.support_vectors_

array([[ 0.68373455,  0.0488774 , -0.23709621,  0.01686997, -0.22144463,
        -0.18547651, -0.43013893, -0.27241665, -0.38508488, -0.0304932 ,
        -0.03920461,  0.97984896,  0.22443933, -0.07725387, -0.02162182,
         0.13451903,  0.01942884, -0.02275524, -0.0198628 ,  0.0273803 ,
         0.5135781 , -0.2132971 , -0.07484835, -0.00813752, -0.3967954 ,
        -0.55209777, -1.41715509, -0.58011007, -0.81381582, -0.08563459]])

In [28]:
(clf.dual_coef_ @ clf.support_vectors_).shape

(1, 30)

In [29]:
X_train[0].reshape(1, len(X_train[0])).T

array([[1.149e+01],
       [1.459e+01],
       [7.399e+01],
       [4.049e+02],
       [1.046e-01],
       [8.228e-02],
       [5.308e-02],
       [1.969e-02],
       [1.779e-01],
       [6.574e-02],
       [2.034e-01],
       [1.166e+00],
       [1.567e+00],
       [1.434e+01],
       [4.957e-03],
       [2.114e-02],
       [4.156e-02],
       [8.038e-03],
       [1.843e-02],
       [3.614e-03],
       [1.240e+01],
       [2.190e+01],
       [8.204e+01],
       [4.676e+02],
       [1.352e-01],
       [2.010e-01],
       [2.596e-01],
       [7.431e-02],
       [2.941e-01],
       [9.180e-02]])

In [30]:
X_train[0].reshape(1, len(X_train[0])).T.shape

(30, 1)

In [31]:
(clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T

array([[-10.9698231]])

In [32]:
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[1].reshape(1, len(X_train[1])).T + clf.intercept_)[0][0]

4.8991654692802395

A partir daqui não é mais do Thiago

**Encontrando Limites Positivo e Negativo do SVM**

In [33]:
decfun = clf.decision_function(X_train)
lim_pos = decfun[np.argmax(decfun)]
lim_neg = decfun[np.argmin(decfun)]
print("Limite Pos = ",lim_pos, '\nLimite Neg =',lim_neg)

Limite Pos =  9.37321931602485 
Limite Neg = -47.65638399792085


**Preparando variáveis wr, t1, t2**

In [34]:
wr = []
for i in range(1,13):
  wr.append(i*0.04)
print(wr)

[0.04, 0.08, 0.12, 0.16, 0.2, 0.24, 0.28, 0.32, 0.36, 0.4, 0.44, 0.48]


In [35]:
#Total quantity of elements
n_elements = decfun.shape[0]
n_elements

398

In [36]:
t1 = []
t2 = []
for i in range (1,101):
  t1.append(0.01*i*lim_pos)
  t2.append(0.01*i*lim_neg)
#for i in range (1,51):
#  t1.append(0.02*i*lim_pos)
#  t2.append(0.02*i*lim_neg)

In [37]:
dict_reject = {'WR': wr,'T1':t1, 'T2':t2,'E':[],'R':[],'EWRR': []}
dict_reject

{'E': [],
 'EWRR': [],
 'R': [],
 'T1': [0.0937321931602485,
  0.187464386320497,
  0.2811965794807455,
  0.374928772640994,
  0.4686609658012425,
  0.562393158961491,
  0.6561253521217395,
  0.749857545281988,
  0.8435897384422364,
  0.937321931602485,
  1.0310541247627334,
  1.124786317922982,
  1.2185185110832304,
  1.312250704243479,
  1.4059828974037274,
  1.499715090563976,
  1.5934472837242246,
  1.6871794768844728,
  1.7809116700447214,
  1.87464386320497,
  1.9683760563652184,
  2.062108249525467,
  2.1558404426857156,
  2.249572635845964,
  2.3433048290062124,
  2.437037022166461,
  2.5307692153267096,
  2.624501408486958,
  2.7182336016472064,
  2.811965794807455,
  2.905697987967703,
  2.999430181127952,
  3.0931623742882004,
  3.1868945674484492,
  3.2806267606086976,
  3.3743589537689456,
  3.4680911469291944,
  3.561823340089443,
  3.6555555332496916,
  3.74928772640994,
  3.8430199195701884,
  3.936752112730437,
  4.030484305890686,
  4.124216499050934,
  4.217948692211

First Element Iteration Example

In [38]:
#Get Number of Rejected
positive_indexes = np.where(decfun >= dict_reject['T1'][0])
negative_indexes = np.where(decfun < dict_reject['T2'][0])
rejected_indexes = np.where((decfun < dict_reject['T1'][0]) & (decfun >= dict_reject['T2'][0]))
R = rejected_indexes[0].shape[0]
np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

((1, 252), (1, 136), 10)

In [39]:
#Showing Rejected Elements
rejected_indexes,decfun[rejected_indexes[0]],dict_reject['T1'][0],dict_reject['T2'][0]

((array([ 28, 120, 129, 151, 157, 190, 211, 284, 364, 379]),),
 array([-0.01174956, -0.46210051, -0.0729748 , -0.33347919, -0.24845183,
        -0.25014049, -0.43657875, -0.21034102,  0.07450255, -0.23466209]),
 0.0937321931602485,
 -0.4765638399792085)

In [40]:
#Get Number of Misclassifications
class_p = y_train[positive_indexes]
class_n = y_train[negative_indexes]
error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
error_total = (error_p + error_n)/(n_elements - R)
class_p,class_n,error_p,error_n,error_total,

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [41]:
print("Erro = ",error_total," wr = ",dict_reject['WR'][0],' R = ',R, '\nE + wr * R = ',error_total + dict_reject['WR'][0] * R)

Erro =  0.030927835051546393  wr =  0.04  R =  10 
E + wr * R =  0.4309278350515464


First Full Iterations

In [42]:
EwrR_0 = []
for i,t in enumerate(dict_reject['T1']):
  #Get Number of Rejected
  positive_indexes = np.where(decfun >= dict_reject['T1'][i])
  negative_indexes = np.where(decfun < dict_reject['T2'][i])
  rejected_indexes = np.where((decfun < dict_reject['T1'][i]) & (decfun >= dict_reject['T2'][i]))
  R = rejected_indexes[0].shape[0]
  #np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

  #Get Number of Misclassifications
  class_p = y_train[positive_indexes]
  class_n = y_train[negative_indexes]
  error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
  error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
  error_total = (error_p + error_n)/(n_elements - R)
  
  EwrR_0.append(error_total + dict_reject['WR'][0] * R)
  print('(',i+1,')',"Erro = ",error_total," wr = ",dict_reject['WR'][0],' R = ',R, 'E + wrR = ',error_total + dict_reject['WR'][0] * R,' T1 = ',dict_reject['T1'][i], ' T2 = ', dict_reject['T2'][i], ' Error P = ', error_p, ' Error N = ', error_n)
np.argmin(np.array(EwrR_0)), EwrR_0[np.argmin(np.array(EwrR_0))]


( 1 ) Erro =  0.030927835051546393  wr =  0.04  R =  10 E + wrR =  0.4309278350515464  T1 =  0.0937321931602485  T2 =  -0.4765638399792085  Error P =  8  Error N =  4
( 2 ) Erro =  0.0234375  wr =  0.04  R =  14 E + wrR =  0.5834375  T1 =  0.187464386320497  T2 =  -0.953127679958417  Error P =  7  Error N =  2
( 3 ) Erro =  0.016172506738544475  wr =  0.04  R =  27 E + wrR =  1.0961725067385446  T1 =  0.2811965794807455  T2 =  -1.4296915199376254  Error P =  6  Error N =  0
( 4 ) Erro =  0.013850415512465374  wr =  0.04  R =  37 E + wrR =  1.4938504155124654  T1 =  0.374928772640994  T2 =  -1.906255359916834  Error P =  5  Error N =  0
( 5 ) Erro =  0.0113314447592068  wr =  0.04  R =  45 E + wrR =  1.8113314447592068  T1 =  0.4686609658012425  T2 =  -2.3828191998960424  Error P =  4  Error N =  0
( 6 ) Erro =  0.011594202898550725  wr =  0.04  R =  53 E + wrR =  2.1315942028985506  T1 =  0.562393158961491  T2 =  -2.859383039875251  Error P =  4  Error N =  0
( 7 ) Erro =  0.0120120120

(0, 0.4309278350515464)

All Iterations

In [43]:
for i,wr_ in enumerate(dict_reject['WR']):
  EwrR = []
  for i,t in enumerate(dict_reject['T1']):
    #Get Number of Rejected
    positive_indexes = np.where(decfun >= dict_reject['T1'][i])
    negative_indexes = np.where(decfun < dict_reject['T2'][i])
    rejected_indexes = np.where((decfun < dict_reject['T1'][i]) & (decfun >= dict_reject['T2'][i]))
    R = rejected_indexes[0].shape[0]
    #np.array(positive_indexes).shape,np.array(negative_indexes).shape, R

    #Get Number of Misclassifications
    class_p = y_train[positive_indexes]
    class_n = y_train[negative_indexes]
    error_p = np.where(class_p == np.argmin(np.unique(y_train)))[0].shape[0]
    error_n = np.where(class_n == np.argmax(np.unique(y_train)))[0].shape[0]
    error_total = (error_p + error_n)/(n_elements - R)
    
    EwrR.append(error_total + wr_ * R)
    #print('(',i+1,')',"Erro = ",error_total," wr = ",wr_,' R = ',R, 'E + wrR = ',error_total + wr_ * R,' T1 = ',dict_reject['T1'][i], ' T2 = ', dict_reject['T2'][i], ' Error P = ', error_p, ' Error N = ', error_n)
  print(np.argmin(np.array(EwrR)), EwrR[np.argmin(np.array(EwrR))])

0 0.4309278350515464
0 0.8309278350515464
0 1.2309278350515465
0 1.6309278350515464
0 2.0309278350515463
0 2.430927835051546
0 2.8309278350515465
0 3.2309278350515465
0 3.630927835051546
0 4.030927835051546
0 4.430927835051547
0 4.830927835051546


z3 solver thiago

In [47]:
#!pip install z3-solver

     |████████████████████████████████| 54.5 MB 1.3 MB/s 


In [48]:
from z3 import *

In [49]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [50]:
# creating one z3 variable for each feature in the dataset
dict_vars = {}
for feature in cancer.feature_names:
  dict_vars[feature] = Real(feature)

In [ ]:
dict_vars

In [52]:
dict_vars['area error']

area error

In [53]:
constraints = Solver()

In [54]:
constraints.add(dict_vars['area error'] > 2)
constraints.add(dict_vars['compactness error'] < 10)
constraints.add(dict_vars['compactness error'] > 2)
constraints.add(dict_vars['area error'] * dict_vars['compactness error'] == 27)

In [55]:
constraints.check()

sat

In [56]:
constraints.model()

[compactness error = 3, area error = 9]

Implementing SVM function for Z3 Solver

In [57]:
X_train.shape

(398, 30)

In [58]:
#SVM Decision Function answer for the first element of training set and the actual first element
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_), decfun[0]

(array([[3.55261264]]), 3.552612638406506)

In [60]:
clf.dual_coef_.shape,clf.support_vectors_.shape,X_train[0].reshape(1, len(X_train[0])).T.shape, clf.intercept_

((1, 43), (43, 30), (30, 1), array([14.52243574]))

In [59]:
#SVM Decision Function answer for all elements of training set
for i in range(0,X_train.shape[0]):
  #print(i, ' : ',((clf.dual_coef_ @ clf.support_vectors_) @ X_train[i].reshape(1, len(X_train[0])).T + clf.intercept_))
  pass

To z3

In [118]:
np.RealVal = np.vectorize(RealVal) # simple mapping of functions over a vector
np.RealVector = np.vectorize(RealVector) 

In [119]:
test_real = Real('X_train')

In [120]:
test_real

X_train

In [121]:
z3_dual_coef = np.RealVal(clf.dual_coef_)
z3_support_vectors = np.RealVal(clf.support_vectors_)
z3_X_Train = np.RealVal(X_train)
#z3_X_Train = np.z3Real(X_train[0])
z3_intercept_ = np.RealVal(clf.intercept_)

In [122]:
#O Z3 possui um problema de arredondamento (Floating Point) e não consegue chegar ao valor exato da função de decisão, mas até a oitava casa.
first_element = ((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0]
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] > 3.552612640)
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] > 3.5526126409)
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] <= first_element)
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] == first_element)
first_element

proved
counterexample
[]
proved
counterexample
[]


3.552612640902959

In [123]:
expression = simplify (((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0])
expression

1776306320225397058985796096969/500000000000000000000000000000

In [124]:
expression.numerator_as_long()/expression.denominator_as_long()

3.552612640450794

In [125]:
get_decimal = float("{0:.9f}".format(expression.numerator_as_long()/expression.denominator_as_long()))
get_decimal

3.55261264

In [126]:
clf.intercept_[0],z3_intercept_[0],3630608935567563/250000000000000

(14.522435742270252, 3630608935567563/250000000000000, 14.522435742270252)

In [127]:
rejected_indexes = np.where((decfun < dict_reject['T1'][0]) & (decfun >= dict_reject['T2'][0]))
decfun[rejected_indexes[0]]

array([-0.01174956, -0.46210051, -0.0729748 , -0.33347919, -0.24845183,
       -0.25014049, -0.43657875, -0.21034102,  0.07450255, -0.23466209])

In [ ]:
for index in rejected_indexes[0]:
  expression = simplify (((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[index].reshape(1, len(z3_X_Train[index])).T + z3_intercept_)[0][0])
  expression = expression.numerator_as_long()/expression.denominator_as_long()
  
  print(expression, decfun[index], abs(abs(expression) - abs(decfun[index])))
  #expression = round(expression,6)
  #decfun_value = round(decfun[index],6)
  #print(expression, decfun_value, abs(abs(expression) - abs(decfun_value)))

Implemeting Solver's Restrictions

In [129]:
solver = Solver()

In [130]:
z3_X_Train[rejected_indexes[0][0]]

array([1499/100, 126/5, 4777/50, 3494/5, 9387/100000, 5131/100000,
       1199/50000, 2899/100000, 313/2000, 172/3125, 607/500, 547/250,
       8077/1000, 106, 6883/1000000, 547/50000, 909/50000, 1917/100000,
       3941/500000, 877/500000, 1499/100, 126/5, 4777/50, 3494/5,
       9387/100000, 5131/100000, 1199/50000, 2899/100000, 313/2000,
       172/3125], dtype=object)

Hora do Show

In [278]:
first_element = ((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0]
first_element

3.552612640902959

In [279]:
np.RealVal = np.vectorize(RealVal) 
np.RealVector = np.vectorize(RealVector) 

In [280]:
z3_dual_coef = np.RealVal(clf.dual_coef_)
z3_support_vectors = np.RealVal(clf.support_vectors_)
z3_X_Train = np.RealVal(X_train)
z3_intercept_ = np.RealVal(clf.intercept_)

In [281]:
prove(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train[0].reshape(1, len(z3_X_Train[0])).T + z3_intercept_)[0][0] <= first_element)

proved


In [311]:
X_train[0].shape

(30,)

In [282]:
#X_train_t = X_train[0].reshape(1, len(X_train[0])).T

In [313]:
((clf.dual_coef_ @ clf.support_vectors_) @ X_train[0].reshape(1, len(X_train[0])).T + clf.intercept_)[0][0], first_element

(3.552612640902959, 3.552612640902959)

In [369]:
X_train_2 = X_train[0]
X_train_2[0] = 2

In [370]:
expressao = simplify (((z3_dual_coef @ z3_support_vectors) @ X_train_2.reshape(1, len(X_train_2)).T + z3_intercept_)[0][0])

In [371]:
expressao.numerator_as_long()/expressao.denominator_as_long()

-2.936028237851599

In [314]:
prove(((z3_dual_coef @ z3_support_vectors) @ X_train[0].reshape(1, len(X_train[0])).T + z3_intercept_)[0][0] <= first_element)

proved


In [ ]:
for i in range (0, len(X_train[0])):
  print('solver.add(z3_X_Train[',i,'] = X_train[0][',i,']')

In [286]:
z3_X_Train = np.RealVector('x',X_train.shape[1])
z3_X_Train,z3_X_Train[0]

(array([x__0, x__1, x__2, x__3, x__4, x__5, x__6, x__7, x__8, x__9, x__10,
        x__11, x__12, x__13, x__14, x__15, x__16, x__17, x__18, x__19,
        x__20, x__21, x__22, x__23, x__24, x__25, x__26, x__27, x__28,
        x__29], dtype=object), x__0)

In [288]:
z3_X_Train[:3] @ z3_X_Train[:3]

x__0*x__0 + x__1*x__1 + x__2*x__2

In [325]:
X_train[0][1]

14.59

In [328]:
solver = Solver()
solver.add(z3_X_Train[0] == X_train[0][ 0 ])
solver.add(z3_X_Train[:1] @ z3_X_Train[:1] > 130)
solver.check()
solver.model()

[x__0 = 1149/100]

In [379]:
solver = Solver()

solver.add(z3_X_Train[0] > -5)
solver.add(z3_X_Train[0] < 0)
solver.add(z3_X_Train[1] == X_train[0][1])
solver.add(z3_X_Train[2] == X_train[0][2])
solver.add(z3_X_Train[3] == X_train[0][3])
solver.add(z3_X_Train[4] == X_train[0][4])
solver.add(z3_X_Train[5] == X_train[0][5])
solver.add(z3_X_Train[6] == X_train[0][6])
solver.add(z3_X_Train[7] == X_train[0][7])
solver.add(z3_X_Train[8] == X_train[0][8])
solver.add(z3_X_Train[9] == X_train[0][9])
solver.add(z3_X_Train[10] == X_train[0][10])
solver.add(z3_X_Train[11] == X_train[0][11])
solver.add(z3_X_Train[12] == X_train[0][12])
solver.add(z3_X_Train[13] == X_train[0][13])
solver.add(z3_X_Train[14] == X_train[0][14])
solver.add(z3_X_Train[15] == X_train[0][15])
solver.add(z3_X_Train[16] == X_train[0][16])
solver.add(z3_X_Train[17] == X_train[0][17])
solver.add(z3_X_Train[18] == X_train[0][18])
solver.add(z3_X_Train[19] == X_train[0][19])
solver.add(z3_X_Train[20] == X_train[0][20])
solver.add(z3_X_Train[21] == X_train[0][21])
solver.add(z3_X_Train[22] == X_train[0][22])
solver.add(z3_X_Train[23] == X_train[0][23])
solver.add(z3_X_Train[24] == X_train[0][24])
solver.add(z3_X_Train[25] == X_train[0][25])
solver.add(z3_X_Train[26] == X_train[0][26])
solver.add(z3_X_Train[27] == X_train[0][27])
solver.add(z3_X_Train[28] == X_train[0][28])
solver.add(z3_X_Train[29] == X_train[0][29])

In [347]:
first_element

3.552612640902959

In [380]:
solver.add(((z3_dual_coef @ z3_support_vectors) @ z3_X_Train.reshape(1, len(z3_X_Train)).T + z3_intercept_)[0][0] < 0)

In [381]:
solver.check(), solver.model()

(sat, [x__16 = 1039/25000,
  x__4 = 523/5000,
  x__20 = 62/5,
  x__21 = 219/10,
  x__15 = 1057/50000,
  x__6 = 1327/25000,
  x__23 = 2338/5,
  x__2 = 7399/100,
  x__19 = 1807/500000,
  x__13 = 717/50,
  x__14 = 4957/1000000,
  x__10 = 1017/5000,
  x__1 = 1459/100,
  x__9 = 3287/50000,
  x__24 = 169/1250,
  x__11 = 583/500,
  x__8 = 1779/10000,
  x__5 = 2057/25000,
  x__22 = 2051/25,
  x__0 = -1,
  x__26 = 649/2500,
  x__27 = 7431/100000,
  x__25 = 201/1000,
  x__3 = 4049/10,
  x__12 = 1567/1000,
  x__28 = 2941/10000,
  x__7 = 1969/100000,
  x__18 = 1843/100000,
  x__29 = 459/5000,
  x__17 = 4019/500000])

In [346]:
solver.check(), solver.model()

(sat, [x__16 = 1039/25000,
  x__4 = 523/5000,
  x__20 = 62/5,
  x__21 = 219/10,
  x__15 = 1057/50000,
  x__6 = 1327/25000,
  x__23 = 2338/5,
  x__2 = 7399/100,
  x__19 = 1807/500000,
  x__13 = 717/50,
  x__14 = 4957/1000000,
  x__10 = 1017/5000,
  x__1 = 1459/100,
  x__9 = 3287/50000,
  x__24 = 169/1250,
  x__11 = 583/500,
  x__8 = 1779/10000,
  x__5 = 2057/25000,
  x__22 = 2051/25,
  x__0 = -1,
  x__26 = 649/2500,
  x__27 = 7431/100000,
  x__25 = 201/1000,
  x__3 = 4049/10,
  x__12 = 1567/1000,
  x__28 = 2941/10000,
  x__7 = 1969/100000,
  x__18 = 1843/100000,
  x__29 = 459/5000,
  x__17 = 4019/500000])